package httpapi

import (
	"fmt"

	"github.com/el-amin-dev/barqr/internal/config"
	"github.com/el-amin-dev/barqr/internal/render"
	"github.com/el-amin-dev/barqr/internal/writer"
)

// Defaults maps every request path that has a real, expressible default onto
// that default, read from the code that actually applies it.
//
// Nothing here is a retyped literal. A default typed out a second time is a
// second source of truth, and the two drift apart silently — which is exactly
// what happened to style.hri: the service defaulted it on, docs/API.md said so
// correctly, and the generated OpenAPI document said nothing at all, so a
// caller reading the spec and assuming false got true. Sourcing the value from
// render.DefaultStyle() and friends means the document cannot make that claim
// wrongly, and a test asserts the document and this map agree in both
// directions.
//
// It takes the configuration because two of the defaults are per-instance: a
// document generated by one deployment describes that deployment, which is the
// whole point of generating it at request time rather than committing a
// snapshot (ADR-013).
func Defaults(cfg *config.Config) map[string]any {
	st := render.DefaultStyle()
	out := writer.DefaultOutputOpts(cfg.DefaultFormat)

	return map[string]any{
		"encode.ecc": cfg.DefaultECC,

		"style.module":       st.Module,
		"style.eye":          st.Eye,
		"style.eye_ball":     st.EyeBall,
		"style.fg":           render.HexColor(st.FG),
		"style.bg":           render.HexColor(st.BG),
		"style.hri":          st.HRI,
		"style.hri_size":     st.HRISize,
		"style.hri_font":     st.HRIFont,
		"style.logo_scale":   render.DefaultLogoScale,
		"style.excavate":     false,
		"style.logo_padding": 0,
		"style.frame_width":  render.DefaultFrameWidth,

		"output.format":  cfg.DefaultFormat,
		"output.scale":   out.Scale,
		"output.unit":    string(out.Unit),
		"output.dpi":     out.DPI,
		"output.quality": out.Quality,

		"meta.attachment": false,
	}
}

// defaultsProse lists the paths whose default is a sentence rather than a
// value, with the exact words docs/API.md uses for them.
//
// Together with Defaults this is a total partition of the settable paths that
// have any default at all, which is what lets a test fail on a NEW field that
// has neither — the drift this whole file exists to prevent, caught at the
// moment the field is added rather than by the next person to read the spec.
func defaultsProse() map[string]string {
	return map[string]string{
		"encode.version":      "auto",
		"encode.mask":         "auto",
		"encode.quiet_zone":   "the symbology's own",
		"style.bar_height":    "auto",
		"style.frame_color":   "the foreground",
		"style.caption_color": "the foreground",
	}
}

// applyDefaults walks a JSON-Schema property tree and stamps each leaf named
// in defaults with its value. Paths are dotted, matching the request's own
// dot-notation, so the map reads the same way a caller writes a query string.
func applyDefaults(schema map[string]any, defaults map[string]any) {
	var walk func(node map[string]any, prefix string)
	walk = func(node map[string]any, prefix string) {
		props, ok := node["properties"].(map[string]any)
		if !ok {
			return
		}
		for name, raw := range props {
			child, ok := raw.(map[string]any)
			if !ok {
				continue
			}
			path := name
			if prefix != "" {
				path = prefix + "." + name
			}
			if v, has := defaults[path]; has {
				child["default"] = v
			}
			walk(child, path)
		}
	}
	walk(schema, "")
}

// defaultString renders a default the way docs/API.md writes it, so the
// markdown and the generated document can be compared without each side
// inventing its own formatting.
func defaultString(v any) string {
	switch t := v.(type) {
	case string:
		return t
	case bool:
		return fmt.Sprintf("%t", t)
	case float64:
		// Trim a trailing .0 so a size of two reads as "2", not "2.0".
		if t == float64(int64(t)) {
			return fmt.Sprintf("%d", int64(t))
		}
		return fmt.Sprintf("%g", t)
	default:
		return fmt.Sprintf("%v", t)
	}
}
